const COLORS = {
  NEUTRAL: {
    _00: '#FFFFFF',
    _01: '#F9FAFA',
    _02: '#F4F5F6',
    _03: '#EDEDF0',
    _04: '#AAAAAB',
    _05: '#808893',
    _09: '#59595A',
    _10: '#50565E',
    _20: '#262627',
    _ST_10: 'rgba(28, 30, 45, 0.2)',
  },
  BLUE: {
    _06: '#006FFF',
    _07: '#0059CC',
  },
  RED: {
    _03: '#F9B0B2',
    _06: '#F03A3E',
  },
  TRANSPARENT: '#FFFFFF00',
};

export const HEADER_COLOR = COLORS.NEUTRAL._05;
export const HEADER_BACKGROUND_COLOR = COLORS.NEUTRAL._02;
export const LOGO_COLOR = COLORS.NEUTRAL._10;
export const LOGO_COLOR_HOVER = COLORS.BLUE._06;
export const LOGO_BACKGROUND_COLOR_HOVER = COLORS.NEUTRAL._00;
export const LOGO_COLOR_FOCUS = COLORS.NEUTRAL._10;
export const LOGO_BACKGROUND_COLOR_FOCUS = COLORS.NEUTRAL._02;
export const LOGO_OUTLINE_COLOR_FOCUS = COLORS.BLUE._06;

export const TEXT_INPUT_COLOR = COLORS.NEUTRAL._20;
export const TEXT_INPUT_BACKGROUND_COLOR = COLORS.NEUTRAL._02;
export const TEXT_INPUT_PLACEHOLDER_COLOR = COLORS.NEUTRAL._05;
export const TEXT_INPUT_COLOR_HOVER = COLORS.NEUTRAL._20;
export const TEXT_INPUT_BACKGROUND_COLOR_HOVER = COLORS.NEUTRAL._03;
export const TEXT_INPUT_COLOR_FOCUS = COLORS.NEUTRAL._20;
export const TEXT_INPUT_BACKGROUND_COLOR_FOCUS = COLORS.NEUTRAL._02;
export const TEXT_INPUT_OUTLINE_COLOR_FOCUS = COLORS.BLUE._06;
export const TEXT_INPUT_COLOR_ASIDE = COLORS.NEUTRAL._05;

export const POPOVER_BACKGROUND_COLOR = COLORS.NEUTRAL._00;
export const POPOVER_SHADOW_COLOR = COLORS.NEUTRAL._ST_10;

export const POPOVER_ITEM_COLOR = COLORS.NEUTRAL._10;
export const POPOVER_ITEM_BACKGROUND_COLOR_HIGHLIGHTED = COLORS.NEUTRAL._02;
export const POPOVER_ITEM_OUTLINE_COLOR_HIGHLIGHTED = COLORS.BLUE._06;
export const POPOVER_ITEM_ASIDE_COLOR = COLORS.NEUTRAL._05;

export const BUTTON_COLOR = COLORS.NEUTRAL._10;
export const BUTTON_BACKGROUND_COLOR = COLORS.TRANSPARENT;
export const BUTTON_COLOR_HOVER = COLORS.NEUTRAL._10;
export const BUTTON_BACKGROUND_COLOR_HOVER = COLORS.NEUTRAL._02;
export const BUTTON_COLOR_ACTIVE = COLORS.BLUE._06;
export const BUTTON_BACKGROUND_COLOR_ACTIVE = COLORS.NEUTRAL._01;
export const BUTTON_OUTLINE_COLOR_FOCUS = COLORS.BLUE._06;
export const BUTTON_COLOR_DISABLED = COLORS.NEUTRAL._04;
export const BUTTON_BACKGROUND_COLOR_DISABLED = COLORS.NEUTRAL._00;

export const BUTTON_DESTRUCTIVE_COLOR = COLORS.RED._06;
export const BUTTON_DESTRUCTIVE_BACKGROUND_COLOR = COLORS.TRANSPARENT;
export const BUTTON_DESTRUCTIVE_COLOR_HOVER = COLORS.RED._06;
export const BUTTON_DESTRUCTIVE_BACKGROUND_COLOR_HOVER = COLORS.NEUTRAL._02;
export const BUTTON_DESTRUCTIVE_COLOR_ACTIVE = COLORS.RED._06;
export const BUTTON_DESTRUCTIVE_BACKGROUND_COLOR_ACTIVE = COLORS.NEUTRAL._01;
export const BUTTON_DESTRUCTIVE_OUTLINE_COLOR_FOCUS = COLORS.RED._06;
export const BUTTON_DESTRUCTIVE_COLOR_DISABLED = COLORS.RED._03;

export const BUTTON_CTA_COLOR = COLORS.BLUE._06;
export const BUTTON_CTA_BACKGROUND_COLOR = COLORS.TRANSPARENT;
export const BUTTON_CTA_COLOR_HOVER = COLORS.BLUE._07;
export const BUTTON_CTA_OUTLINE_COLOR_FOCUS = COLORS.BLUE._06;

export const CHECKBOX_CHECKMARK_COLOR = COLORS.NEUTRAL._00;
export const CHECKBOX_BACKGROUND_COLOR = COLORS.TRANSPARENT;
export const CHECKBOX_BORDER_COLOR = COLORS.NEUTRAL._05;
export const CHECKBOX_BACKGROUND_COLOR_CHECKED = COLORS.BLUE._06;

export const PRODUCT_CARD_COLOR = COLORS.NEUTRAL._20;
export const PRODUCT_CARD_BACKGROUND_COLOR = COLORS.NEUTRAL._00;
export const PRODUCT_CARD_BORDER_COLOR = COLORS.NEUTRAL._03;
export const PRODUCT_CARD_COLOR_HOVER = COLORS.NEUTRAL._20;
export const PRODUCT_CARD_BACKGROUND_COLOR_HOVER = COLORS.NEUTRAL._01;
export const PRODUCT_CARD_OUTLINE_COLOR_FOCUS = COLORS.BLUE._06;

export const PRODUCT_CARD_IMAGE_BACKGROUND_COLOR = COLORS.NEUTRAL._01;
export const PRODUCT_CARD_IMAGE_BACKGROUND_COLOR_HOVER = COLORS.NEUTRAL._02;

export const PRODUCT_CARD_CHIP_COLOR = COLORS.BLUE._06;
export const PRODUCT_CARD_CHIP_BACKGROUND_COLOR = COLORS.NEUTRAL._00;
export const PRODUCT_CARD_COLOR_ASIDE = COLORS.NEUTRAL._05;

export const LIST_BACKGROUND_COLOR = COLORS.NEUTRAL._00;
export const LIST_HEADING_COLOR = COLORS.NEUTRAL._20;
export const LIST_ITEM_BORDER_COLOR = COLORS.NEUTRAL._03;
export const LIST_ITEM_COLOR = COLORS.NEUTRAL._10;
export const LIST_ITEM_BACKGROUND_COLOR_HOVER = COLORS.NEUTRAL._02;
export const LIST_ITEM_OUTLINE_COLOR_FOCUS = COLORS.BLUE._06;

export const PRODUCT_TITLE_COLOR = COLORS.NEUTRAL._20;
export const PRODUCT_LINE_NAME_COLOR = COLORS.NEUTRAL._05;
export const PRODUCT_DETAIL_ITEM_TITLE_COLOR = COLORS.NEUTRAL._20;
export const PRODUCT_DETAIL_ITEM_VALUE_COLOR = COLORS.NEUTRAL._05;

export const JSON_COLOR = COLORS.NEUTRAL._20;
export const JSON_BACKGROUND_COLOR = COLORS.NEUTRAL._02;
